import { Course } from '../types/eduflow';

function formatDateToICS(date: Date): string {
  return date.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '');
}

function formatDateOnlyToICS(dateStr: string): string {
  return dateStr.replace(/-/g, '');
}

export function generateCourseICS(course: Course): string {
  const now = new Date();
  const nowStr = formatDateToICS(now);

  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//EduFlow//Exam Prep Planner//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:EduFlow - ${course.title}`,
    'X-WR-TIMEZONE:UTC',
  ];

  // 1. Add Exam Date as a high-priority all-day milestone
  if (course.examDate) {
    const examDateStr = formatDateOnlyToICS(course.examDate);
    lines.push(
      'BEGIN:VEVENT',
      `UID:exam-${course.id}-${Date.now()}@eduflow.app`,
      `DTSTAMP:${nowStr}`,
      `DTSTART;VALUE=DATE:${examDateStr}`,
      `SUMMARY:🎯 EXAM DAY: ${course.title} (${course.code})`,
      `DESCRIPTION:Target certification exam date for ${course.title}. Good luck! Generated by EduFlow.`,
      'STATUS:CONFIRMED',
      'PRIORITY:1',
      'BEGIN:VALARM',
      'TRIGGER:-P1D',
      'ACTION:DISPLAY',
      `DESCRIPTION:Reminder: ${course.title} Exam is tomorrow!`,
      'END:VALARM',
      'END:VEVENT'
    );
  }

  // 2. Add remaining agenda tasks as scheduled study blocks starting today
  course.agenda
    .filter(task => task.status !== 'completed')
    .forEach((task, index) => {
      const startTime = new Date(now.getTime() + (index + 1) * 24 * 60 * 60 * 1000); // spread across upcoming days at 9:00 AM
      startTime.setHours(9, 0, 0, 0);
      const endTime = new Date(startTime.getTime() + task.durationMinutes * 60 * 1000);

      lines.push(
        'BEGIN:VEVENT',
        `UID:task-${task.id}-${index}@eduflow.app`,
        `DTSTAMP:${nowStr}`,
        `DTSTART:${formatDateToICS(startTime)}`,
        `DTEND:${formatDateToICS(endTime)}`,
        `SUMMARY:📖 [${task.type.toUpperCase()}] ${task.title}`,
        `DESCRIPTION:EduFlow Study Session (${task.durationMinutes} min) for ${course.title}.\\nType: ${task.type}`,
        'STATUS:CONFIRMED',
        'BEGIN:VALARM',
        'TRIGGER:-PT15M',
        'ACTION:DISPLAY',
        `DESCRIPTION:Study Session in 15 mins: ${task.title}`,
        'END:VALARM',
        'END:VEVENT'
      );
    });

  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}

export function downloadCourseICS(course: Course): void {
  const icsContent = generateCourseICS(course);
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${course.code.toLowerCase() || 'eduflow'}-study-plan.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
